version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - dupl
    - err113
    - errcheck
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godoclint
    - godox
    - gosec
    - govet
    - iface
    - intrange
    - makezero
    - mirror
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - wrapcheck

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    iface:
      enable:
        - identical # Identifies interfaces in the same package that have identical method sets.
        - unused # Identifies interfaces that are not used anywhere in the same package where the interface is defined.
        - opaque # Identifies functions that return interfaces, but the actual returned value is always a single concrete implementation.

    tagliatelle:
      case:
        rules:
          json: camel
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - err113
          - forcetypeassert  # Tests can use unchecked assertions
          - goconst
          - gosec
          - nilnil
          - perfsprint    # Performance optimizations not critical in tests
          - testpackage   # Internal tests need access to private members
          - unparam       # Test helper return values may not always be used

      # Singleton pattern globals are intentional
      - path: internal/interpreter/object\.go
        text: "(NULL|TRUE|FALSE|BREAK|CONTINUE) is a global variable"
        linters:
          - gochecknoglobals

      # Method registry global is intentional
      - path: internal/interpreter/interpreter\.go
        text: "methodRegistry is a global variable"
        linters:
          - gochecknoglobals

      # Parser precedence table is intentional global
      - path: internal/parser/parser\.go
        text: "precedences is a global variable"
        linters:
          - gochecknoglobals

      # Token keywords map is intentional global
      - path: internal/token/token\.go
        text: "keywords is a global variable"
        linters:
          - gochecknoglobals

      # Built-in function globals are intentional
      - path: internal/stdlib/builtins\.go
        text: "(Println|Typeof|Integer|Float|String|Boolean|ErrorModel) is a global variable"
        linters:
          - gochecknoglobals

      # CLI file reading is expected behavior
      - path: cmd/tsl/main\.go
        text: "G304"
        linters:
          - gosec

      # Accept current complexity for MVP
      - text: "has complex nested blocks"
        linters:
          - nestif

      # Group comments for token/const blocks are acceptable
      - path: internal/token/token\.go
        text: "godoc should start with symbol name"
        linters:
          - godoclint

      # Minor optimizations not critical for MVP
      - text: ".*"
        linters:
          - prealloc

      # Interface method implementations don't need individual comments
      # The interfaces themselves (Node, Object) are documented with method descriptions
      - path: internal/(ast|interpreter)/
        text: "exported method .*(TokenLiteral|String|Type|Inspect) should have comment"
        linters:
          - revive

      # TokenType naming is acceptable (common pattern in parsers)
      - path: internal/token/token\.go
        text: "type name will be used as token.TokenType"
        linters:
          - revive

      # Performance sprint optimizations not critical for MVP
      - text: "(integer-format|bool-format)"
        linters:
          - perfsprint

      # Evaluation functions return Object interface by design
      - path: internal/interpreter/(interpreter|types)\.go
        text: "function return 'Object' interface"
        linters:
          - iface

formatters:
  enable:
    - gofmt
