version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Essential linters
    - errcheck
    - govet
    - ineffassign
    - unused

    # Additional useful linters
    - bodyclose
    - errorlint
    - goconst
    - gocritic
    - misspell
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - gocognit
        - gosec

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  max-issues-per-linter: 0
  max-same-issues: 0
